import Head from 'next/head'
import Topbar from '@/components/topbar'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import logo from '@/images/cash-in-hand-icon.png';


export default function Home() {
  return (
    <>
      <Head>
        <title>Modern Funding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logo} />
      </Head>
      <main className={styles.main}>

        <Topbar/>

      </main>
    </>
  )
}
