import Head from 'next/head'
import Topbar from '@/components/topbar'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import LandingPage from '@/components/landing_page'

export default function Home(props) {
  
    const router = useRouter();
    const user = router.query;

    
    return (
        <>
        <Head>
        <title>Modern Funding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href='favicon.png' />
        </Head>
        <main className={styles.homeMain}>

            <Topbar
                pageTitle="Home"
            />


            <LandingPage />

        </main>
        </>
    )
}


